name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Archive artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ffriends-app
        path: |
          ./
          !vendor
          !var
          !.*

  deploy:

    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: ffriends-app

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: vps-f9de4d18.vps.ovh.net
          username: ${{ secrets.DEPLOY_SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "./*"
          target: "/home/ffriends/dev"

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
